name: Build
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'unbuilt-v*' # Push events to matching unbuilt-v*, i.e. unbuilt-v1.0.0

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Set RELEASE_VERSION environment variable
        run: echo "RELEASE_VERSION=${GITHUB_REF:18}" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: main

      - name: Checkout release branch
        uses: actions/checkout@v2
        with:
          path: release
          ref: my-branch

      - uses: actions/setup-node@v1
        with:
          node-version: '13.x'

      - name: NPM Build
        run: |
          cd ./main
          npm ci
          npm run build

      - name: Copy Module to Release Working Dir
        run: |
          cp -r ./main/farmos_vue_demo_page/* ./release/

      - name: Push Changes to Release Branch
        run: |
          cd ./release
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Release ${{ env.RELEASE_VERSION }}"
          git push
